// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../js/helloworld.js', ['test.HelloWorld.ClassTest'], ['jquery'], false);
goog.addDependency('../js/jquery.js', ['jquery'], [], false);
